name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: genetic_simulator
        environment-file: safeld.yaml
        use-mamba: true

    - name: Build project
      shell: bash -l {0}
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)

    - name: Test basic functionality
      shell: bash -l {0}
      run: |
        cd build
        ./safeld --help
        
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: safeld-linux
        path: build/safeld

